import Head from 'next/head'
import Layout from '@/Components/Layout'
import Image from 'next/image'
import profilePic from "../../public/images/profile/developer-pic-1.png";
import { LinkArrow } from '@/Components/Icon';
import HireMe from '@/Components/HireMe';
import Link from 'next/link';
import AnimatedText from '@/Components/AnimatedText';



export default function Home() {
  return (
    <>
      <Head>
        <title>awkwardpy</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>

        <Layout className='pt-0'>
        <div className='flex items-center justify-between w-full'>
          <div className='w-1/2'>
            <Image  alt='awkwardpy' className='w-full h-auto '
            priority
            sizes='(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw'
            />
          </div>
          <div className='w-1/2 flex flex-col items-center self-center'>
            <AnimatedText text="Hey, I'm awkwardpy!" className='!text-6xl !text-left'/>
            <p className='my-4 text-base font-medium '>
            As a dedicated learner in web development, I'm currently focused on JavaScript and Python. While navigating my journey toward becoming a full-stack developer, I'm committed to crafting innovative web applications. Explore my progress through recent projects and articles showcasing my growing expertise.     
            </p>
            <div className='flex items-center self-start mt-2'>
              <Link href="/dummy.pdf" target={"_blank"} 
             className={"flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light"}
            
              download ={true}
              >Resume <LinkArrow className={"w-6 ml-1"} />
              </Link>
              <Link href="mailto:awkwardpy@gmail.com" target={"_blank"}
              className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light"
              >Contact</Link>
            </div>
          </div>
        </div>
        </Layout>
        <HireMe />
      </main>
    </>
  )
}
